// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqqinjzkbzrnztxrggyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcWluanprYnpybnp0eHJnZ3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjIwMDUsImV4cCI6MjA2ODIzODAwNX0.NHflO-4nF3xsdELip5z1mH4Y-0lrB3BashCAhLwSCCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});